FROM python:3.9-slim

WORKDIR /app

# Copy the directory
COPY . ${WORKDIR}

# install the dependencies
RUN apt-get update && \
    apt-get install -y build-essential gcc netcat-openbsd && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    chmod +x ./entrypoint.sh

EXPOSE 8020

ENTRYPOINT ["/app/entrypoint.sh"]