name: create-pr

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    name: create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Make changes to pull request here,
      # see https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        # with:
        #   title: "IT worked"
        #   branch: "${{ github.ref_name }}-auto"
        #   # base: "{{ github.ref_name }}"