FROM openjdk:21-jdk-slim

WORKDIR /app

ARG EULA
ARG MEMORY

COPY . $WORKDIR

RUN echo "eula=${EULA}" > eula.txt

EXPOSE 25565

RUN echo "eula=true" > eula.txt

ENV MEMORY=${MEMORY}

ENTRYPOINT ["java", "-Xmx1024M", "-Xms1024M", "-jar", "server.1.21.1.jar", "nogui"]