FROM python:3.6-slim

WORKDIR /app

COPY . /app

RUN apt-get update && \
    apt-get install -y build-essential && \
    python -m pip install --upgrade pip  && \
    pip install -r requirements.txt


RUN python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py collectstatic --noinput

RUN chmod +x /app/entrypoint.sh  

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.sh"]