FROM node:20.9.0 AS build

WORKDIR /app

COPY . /app

RUN yarn install && \
    node set-env.js && \
    yarn build 


FROM nginx:1.26.2-alpine
COPY --from=build /app/dist/angular-conduit /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80