FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

WORKDIR /app/babyshop_app

ARG DJANGO_SUPERUSER_USERNAME
ARG DJANGO_SUPERUSER_EMAIL
ARG DJANGO_SUPERUSER_PASSWORD

RUN python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py collectstatic --noinput

RUN python manage.py createsuperuser --noinput --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL}

RUN echo "from django.contrib.auth import get_user_model; \
User = get_user_model(); \
user = User.objects.get(username='${DJANGO_SUPERUSER_USERNAME}'); \
user.set_password('${DJANGO_SUPERUSER_PASSWORD}'); \
user.save();" | python manage.py shell

EXPOSE 8025

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8025"]