name: CI/CD Pipeline

on:
  push:
    branches: ["conduit-deployment"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: |
          echo "Logging into DockerHub..."
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
          echo "Successfully logged into DockerHub."

      - name: Build & Push conduit-frontend
        run: |
          echo "Building the conduit-frontend image and tagging the conduit-frontend image..."

          docker build -t conduit-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker tag conduit-frontend:latest "${{ vars.DOCKER_USERNAME }}/conduit-frontend:latest"
          docker tag conduit-frontend:latest "${{ vars.DOCKER_USERNAME }}/conduit-frontend:v1.0"

          echo "Pushing the conduit-frontend image to DockerHub..."

          docker push "${{ vars.DOCKER_USERNAME }}/conduit-frontend:latest"
          docker push "${{ vars.DOCKER_USERNAME }}/conduit-frontend:v1.0"

          echo "Successfully built and pushed conduit-frontend."

      - name: Build & Push conduit-backend
        run: |
          echo "Building the conduit-backend image and tagging the conduit-backend image..."

          docker build -t conduit-backend:latest -f ./backend/Dockerfile ./backend
          docker tag conduit-backend:latest "${{ vars.DOCKER_USERNAME }}/conduit-backend:latest"
          docker tag conduit-backend:latest "${{ vars.DOCKER_USERNAME }}/conduit-backend:v1.0"

          echo "Pushing the conduit-backend image to DockerHub..."

          docker push "${{ vars.DOCKER_USERNAME }}/conduit-backend:latest"
          docker push "${{ vars.DOCKER_USERNAME }}/conduit-backend:v1.0"

          echo "Successfully built and pushed conduit-backend."

  transfer:
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose.yaml & sample.env to remote
        run: |
          echo "Copying docker-compose.yaml to the server..."

          scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ vars.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ vars.PROJECT_PATH }}
          scp -o StrictHostKeyChecking=no sample.env ${{ vars.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ vars.PROJECT_PATH }}

          echo "Successfully copied docker-compose.yaml and sample.env to the server."

  deploy:
    runs-on: ubuntu-latest
    needs: [transfer]
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on Server
        run: |
          echo "Starting deployment on the server..."
          ssh -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ secrets.SERVER_IP }} << 'ENDSSH'
            set -e

            cd ${{ vars.PROJECT_PATH }}
            echo "Renaming sample.env to .env..."
            mv sample.env .env

            echo "Stopping and removing existing containers..."
            docker-compose down --remove-orphans || true


            echo "Pulling the latest Docker images..."
            docker-compose pull

            echo "Building Docker containers..."
            docker-compose build

            echo "Starting Docker containers in detached mode..."
            docker-compose up -d --remove-orphans

            echo "Deployment completed successfully."
          ENDSSH

  verify_containers:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify Containers on Server
        run: |
          echo "Verifying if containers are running..."
          ssh -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ secrets.SERVER_IP }} << 'ENDSSH'
            set -e
            cd ${{ vars.PROJECT_PATH }}
            RUNNING_CONTAINERS=$(docker-compose ps | grep "Up" | wc -l)
            if [ "$RUNNING_CONTAINERS" -eq 0 ]; then
              echo "❌ No containers are running!"
              exit 1
            fi
            echo "✅ All containers are running!"
          ENDSSH
